### PR TITLE
Cpe

### PR DESCRIPTION
**Pull request by antmcc49**
This PR implements CPEs into the D3 pipeline, and verify each claim against NIST CPE API

### CODE REVIEW

**Comment by antmcc49** [comment]
@ash Do i need to add anything for conversion of .json to sqlite or CSV?

**Comment by AshleySetter** [comment]
> @ash Do i need to add anything for conversion of .json to sqlite or CSV?

Not for csv conversion, but for csv->sqlite to work you will need to add the cpe field to the sqlite database schema in the manysecured rest-api here: https://github.com/nqminds/many-secured/blob/main/packages/rest/src/schema.js#L33

**Review by AshleySetter — APPROVED** [review]
Looks great to me! Since this is taking the place of the old style of vulnerabilities it's probably worth setting skip_vuln to true always ([here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L131) and [here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L148)

**Comment by antmcc49** [comment]
> Looks great to me! Since this is taking the place of the old style of vulnerabilities it's probably worth setting skip_vuln to true always ([here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L131) and [here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L148)

Good idea!

**Comment by AshleySetter** [comment]
@antmcc49 Also, could you add a test [here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/tests/test_d3_build.py) to test check_cpes_resolve?

**Comment by antmcc49** [comment]
> Looks great to me! Since this is taking the place of the old style of vulnerabilities it's probably worth setting skip_vuln to true always ([here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L131) and [here](https://github.com/TechWorksHub/d3-cli/blob/main/d3-cli/src/d3_scripts/d3_cli.py#L148)

@Ash, just set these to `True`?

**Comment by AshleySetter** [comment]
@antmcc49 Yeah, that'll be fine for now.

**Comment by ash** [comment]
You keep tagging a wrong person.

**Pull request merged**
